version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
    ports:
      - "${DBPORT}:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

